### ISSUE TITLE
make build-all 报错

### ISSUE THREAD

**Issue by licsky** [hylarucoder/playbase#1]
你好，我完全按照你知乎上的文章，配置环境后，到了build-all 这一步时，出现了报错，水平太低实在是搞不懂了，在这里问问你是什么原因。我的也是mac系统，版本是10.13.2。
<img width="1440" alt="wx20180222-200848 2x" src="https://user-images.githubusercontent.com/17822222/36538029-f1dc055a-180c-11e8-8300-a0996aeb1f37.png">

**Comment by hylarucoder** [comment]
我删掉了所有容器/镜像/挂载券/重新build了一下, 没有出现这个问题. 会不会你那边的网络问题? 

建议直接干掉所有容器/镜像/挂载券后重新make

```bash
docker rm $(docker ps -a -q)
docker rmi $(docker images -q) -f
docker volume prune
make build-all
```

我本地删除重新运行了三次, 一切正常, 无法复现这个问题.

**Comment by hylarucoder** [comment]
题主已经从上面的方案中解决了问题,手动关闭一下.

**Comment by YellowDong** [comment]
你好请教一下，我在make build-all时也发生了报错。详情如下：
系统：ubuntu 18.04.3 LTS
系统已经安装了pyenv版本管理工具，并且用pyenv安装了python2.7.11和python3.5.2并设置全局版本为Python2.7.11，创建了py3-daily虚拟环境[
![image](https://user-images.githubusercontent.com/23050255/72423716-b305bb80-37bf-11ea-87a3-d37b24f19692.png)
](url)
在进行到make build-all 时报错如下：
[
![image](https://user-images.githubusercontent.com/23050255/72424332-c36a6600-37c0-11ea-9c0e-4910761b7c86.png)
](url)
第一次报此错误时我按照上面的解决方法：
docker rm `docker ps -a -q`
docker rmi `docker images -q` -f
docker volume prune
make build-all
试了两次还是会报这个错误，麻烦帮忙看一下谢谢！

**Comment by hylarucoder** [comment]
试试 pip3
