### ISSUE TITLE
make build-all error

### ISSUE THREAD

**Issue by ypan87** [hylarucoder/playbase#11]
After I type the command "make build-all", I get an error like this

Collecting futures; python_version == "2.7" (from flower->-r /requirements/base.txt (line 27))
  Downloading https://pypi.doubanio.com/packages/47/04/5fc6c74ad114032cd2c544c575bffc17582295e9cd6a851d6026ab4b2c00/futures-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}

Right now, I just delete the package flower in base.txt, do you have any other solution? Really appreciate if you can answer me this!

**Comment by YellowDong** [comment]
> After I type the command "make build-all", I get an error like this
> 
> Collecting futures; python_version == "2.7" (from flower->-r /requirements/base.txt (line 27))
> Downloading https://pypi.doubanio.com/packages/47/04/5fc6c74ad114032cd2c544c575bffc17582295e9cd6a851d6026ab4b2c00/futures-3.3.0.tar.gz
> Complete output from command python setup.py egg_info:
> This backport is meant only for Python 2.
> It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
> For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
> extras_require={':python_version == "2.7"': ['futures']}
> 
> Right now, I just delete the package flower in base.txt, do you have any other solution? Really appreciate if you can answer me this!

I encountered the same problem, did you find a solution now? my detail msg reference https://github.com/twocucao/YaDjangoBlog/issues/1#issue-299330283

**Comment by maggie1993** [comment]
After I type the command "make build-all", I get an error like this in CentOS7：
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-intel1_2.4.91-2~16.04.1_amd64.deb  Hash Sum mismatch

E: Failed to fetch http://mirrors.aliyun.com/ubuntu/pool/main/libx/libxaw/libxaw7_1.0.13-1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

do you have any other solution? Really appreciate if you can answer me this!
