### ISSUE TITLE
make django-just-up 的时候找不到相关的启动脚本？

### ISSUE THREAD

**Issue by futureshine** [hylarucoder/playbase#4]
您好，我走到 make django-just-up 的时候报这个错误。
![image](https://user-images.githubusercontent.com/12111333/37143092-103922d8-22f5-11e8-88d4-5942f9e872fa.png)
请帮忙看一下，谢谢

**Comment by hylarucoder** [comment]
你好，
1. 是否严格按照我的教程步骤来？
2. 能否多提供一些前后的操作截图？

**Comment by futureshine** [comment]
您好，我改了一下 dev.yml 文件。
![image](https://user-images.githubusercontent.com/12111333/37189047-467dea3e-238d-11e8-94bf-e7399fbbaafd.png)
之前的 base-elasticsearch 和 base-django 都提示找不到image，这个会影响吗？

**Comment by hylarucoder** [comment]
会有的

**Comment by hylarucoder** [comment]
按照步骤来....摸清楚整个环境之前不要动手改代码
