### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by whistlesun** [hylarucoder/playbase#6]
<img width="981" alt="2018-03-15 4 57 58" src="https://user-images.githubusercontent.com/1300426/37453280-2c8a7496-2872-11e8-9f7d-54d14a2f8e7b.png">
<img width="469" alt="2018-03-15 4 58 10" src="https://user-images.githubusercontent.com/1300426/37453281-2ceaccb0-2872-11e8-8564-a4f488b3ac5c.png">

**Comment by hylarucoder** [comment]
你好, 需要安装python 依赖 watchdog
