### ISSUE TITLE
sudo make build-all ->ln error

### ISSUE THREAD

**Issue by xiaoqi521** [hylarucoder/playbase#7]
ln: failed to create symbolic link '/usr/bin/pip': File exists
The command '/bin/sh -c sudo ln -s /usr/bin/pip3 /usr/bin/pip && sudo  ln -s /usr/bin/python3 /usr/bin/python' returned a non-zero code: 1

???

**Comment by xiaoqi521** [comment]
The solution:  
  vim compose/django/Dockerfile-dev  
add:
  RUN sudo rm -rf /usr/bin/pip
  RUN sudo rm -rf /usr/bin/python
  RUN sudo ln -s /usr/bin/pip3 /usr/bin/pip && sudo  ln -s /usr/bin/python3 /usr/bin/python

**Comment by hylarucoder** [comment]
Thx
